### ISSUE TITLE
Luptitude formula is incorrect

### ISSUE THREAD

**Issue by cschreib** [csibrahim/photoz-noisy#1]
Here is what I think is the correct formula (pardon my MatLab):

```
muPsi = mean(sqrt(Psi));
Xn = bsxfun(@rdivide, X, 2*muPsi);
Psi = (2.5/log(10))^2 * bsxfun(@rdivide, Psi./(1 + Xn^2), 4*muPsi^2);
X = -2.5/log(10) * bsxfun(@plus, asinh(Xn), log(muPsi));
```

**Comment by csibrahim** [comment]
Updated, the results are worst however!
RMSE		MLL		FR15		FR05		BIAS
0.329668	0.647652	90.792500	69.910086	0.026324

**Comment by cschreib** [comment]
Ah, indeed! Damn... Thanks for trying it out still. Closing the issue.

**Comment by cschreib** [comment]
It seems the metrics are very close to the linear case. I wonder; do the metrics change significantly if we replace the ```mean``` on the first line by a ```median``` ? I suspect the distribution of errors (```sqrt(Psi)```) might be skewed toward high values, hence that the mean might be much larger than the median; this would in turn drive the transformation to be essentially linear for most objects (indeed for a fixed ```X``` the transformation becomes more and more linear as ```muPsi``` tends to infinity).

**Comment by csibrahim** [comment]
Thanks, just tried it and it is much better 

RMSE	MLL FR15	FR05	BIAS
0.281618	0.728707	91.071304	71.025301	0.014489

I also tried the `mode`, because why not!, and it is the best so far :)
0.260215	0.785316	92.318952	74.566111	0.010083

The log-normal just for reference
0.278301	0.736475	90.841291	71.492298	0.015588

Close enough, bearing in mind this is not a rigors test

**Comment by cschreib** [comment]
Nice! Thanks for checking it out :)
